# Generated by Django 4.0.5 on 2022-06-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['?']},
        ),
    ]
