# Generated by Django 4.0.5 on 2022-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_relation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
