# Generated by Django 4.0.5 on 2022-06-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
