# Generated by Django 4.0.5 on 2022-06-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relation',
            new_name='Foll',
        ),
    ]
